// Generated by gencpp from file cartographer_ros_msgs/WriteAssets.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_WRITEASSETS_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_WRITEASSETS_H

#include <ros/service_traits.h>


#include <cartographer_ros_msgs/WriteAssetsRequest.h>
#include <cartographer_ros_msgs/WriteAssetsResponse.h>


namespace cartographer_ros_msgs
{

struct WriteAssets
{

typedef WriteAssetsRequest Request;
typedef WriteAssetsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteAssets
} // namespace cartographer_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartographer_ros_msgs::WriteAssets > {
  static const char* value()
  {
    return "1ca78fe806c5256bb03c4e35886127f9";
  }

  static const char* value(const ::cartographer_ros_msgs::WriteAssets&) { return value(); }
};

template<>
struct DataType< ::cartographer_ros_msgs::WriteAssets > {
  static const char* value()
  {
    return "cartographer_ros_msgs/WriteAssets";
  }

  static const char* value(const ::cartographer_ros_msgs::WriteAssets&) { return value(); }
};


// service_traits::MD5Sum< ::cartographer_ros_msgs::WriteAssetsRequest> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::WriteAssets > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::WriteAssetsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::WriteAssets >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::WriteAssetsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::WriteAssetsRequest> should match 
// service_traits::DataType< ::cartographer_ros_msgs::WriteAssets > 
template<>
struct DataType< ::cartographer_ros_msgs::WriteAssetsRequest>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::WriteAssets >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::WriteAssetsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartographer_ros_msgs::WriteAssetsResponse> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::WriteAssets > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::WriteAssetsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::WriteAssets >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::WriteAssetsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::WriteAssetsResponse> should match 
// service_traits::DataType< ::cartographer_ros_msgs::WriteAssets > 
template<>
struct DataType< ::cartographer_ros_msgs::WriteAssetsResponse>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::WriteAssets >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::WriteAssetsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_WRITEASSETS_H
