(cl:defpackage cartographer_ros_msgs-srv
  (:use )
  (:export
   "FINISHTRAJECTORY"
   "<FINISHTRAJECTORY-REQUEST>"
   "FINISHTRAJECTORY-REQUEST"
   "<FINISHTRAJECTORY-RESPONSE>"
   "FINISHTRAJECTORY-RESPONSE"
   "STARTTRAJECTORY"
   "<STARTTRAJECTORY-REQUEST>"
   "STARTTRAJECTORY-REQUEST"
   "<STARTTRAJECTORY-RESPONSE>"
   "STARTTRAJECTORY-RESPONSE"
   "SUBMAPQUERY"
   "<SUBMAPQUERY-REQUEST>"
   "SUBMAPQUERY-REQUEST"
   "<SUBMAPQUERY-RESPONSE>"
   "SUBMAPQUERY-RESPONSE"
   "WRITEASSETS"
   "<WRITEASSETS-REQUEST>"
   "WRITEASSETS-REQUEST"
   "<WRITEASSETS-RESPONSE>"
   "WRITEASSETS-RESPONSE"
  ))

